### ISSUE TITLE
Year regex identifier not working

### ISSUE THREAD

**Issue by doctaphil89** [alex-phillips/plex-autocollections#14] opened 2019-02-09 21:17 UTC
Testing using the example from the provided .yaml, multiple movies with that title present in my library, script runs but no movies are added

**Comment by alex-phillips** [comment] 2019-02-09 23:27
What movie are you testing with (so I can test on my end)

**Comment by doctaphil89** [comment] 2019-02-09 23:29
I used Alice in Wonderland and the exact syntax you have in the example yaml you have. I have three different movies with this title (1949, 1951, 2010), i'll attach screen shots

**Comment by doctaphil89** [comment] 2019-02-09 23:32
![1](https://user-images.githubusercontent.com/39143422/52527581-0068d700-2c99-11e9-9c2e-86c76ce65f72.PNG)
![2](https://user-images.githubusercontent.com/39143422/52527582-01016d80-2c99-11e9-93ed-337cbadcd483.PNG)
![3](https://user-images.githubusercontent.com/39143422/52527583-01016d80-2c99-11e9-8cb9-f9ebbd3988f9.PNG)

**Comment by JourneyOver** [comment] 2019-02-14 18:34
Hoping this can get looked into, as it would be nice to get this working so duplicate titles with different years don't get mixed up into collections that they don't belong to.

**Comment by alex-phillips** [comment] 2019-02-19 02:17
This should be fixed in the latest commit.

**Closed as completed by alex-phillips** 2019-02-19 02:17 UTC

**Comment by JourneyOver** [comment] 2019-02-19 06:02
Could probably of created a new issue for number 2 but egh..

1. Year identifier has been confirmed working, so this is great!

2. your `plexapi config file for authentication` stuff seems to be broken though, as I've fiddled with it for a bit trying to get it to work, and someone else has as well and couldn't get it to work either.

I always just ran into the error 
```
Traceback (most recent call last):
  File "main.py", line 14, in <module>
    PLEX_URL = CONFIG.data['auth'].get('server_baseurl', PLEX_URL)
KeyError: 'auth'
```

Edit: Actually just fixed it >.<

it seems that if you remove the
```
PLEX_URL = CONFIG.data['auth'].get('server_baseurl', PLEX_URL)
PLEX_TOKEN = CONFIG.data['auth'].get('server_token', PLEX_TOKEN)
```
bits and just leave the
```
PLEX_URL = ''
PLEX_TOKEN = ''
```
bits to be filled out then it works just fine..

**Comment by alex-phillips** [comment] 2019-02-19 12:42
It seems when I added support for the config vile / ENV variables it broke the old 'manual input' method of logging in and selecting a server. I've added support for both of these methods now.
